export const order = new Map<string,number>([
    ["data-validation-&-encoding", 0],
    ["authentication", 1],
    ["session-management", 2],
    ["authorization", 3],
    ["cryptography", 4],
    ["about", 5],
    ["platform-&-code", 6],
    ["authentication-&-authorization", 7],
    ["network-&-storage", 8],
    ["resilience", 9],
    ["cryptography", 10],
    ["cornucopia", 11],
    ["wild-card", 12],
    // Companion suits
    ["large-language-models", 13],
    ["agentic-ai", 14],
    ["cloud", 15],
    ["frontend", 16],
    ["devops", 17],
    ["social-engineering", 18],
    ["automated-threats", 19],
]);
