export const order = new Map<string,number>([
    ["data-validation-&-encoding", 0],
    ["authentication", 1],
    ["session-management", 2],
    ["authorization", 3],
    ["cryptography", 4],
    ["about", 5],
    ["platform-&-code", 6],
    ["authentication-&-authorization", 7],
    ["network-&-storage", 8],
    ["resilience", 9],
    ["cryptography", 10],
    ["cornucopia", 11],
    ["wild-card", 12],
]);
