# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for npm for cornucopia.owasp.org
  - package-ecosystem: "npm"
    directory: "cornucopia.owasp.org"
    schedule:
      interval: "daily"
  # Maintain dependencies for npm for copi.owasp.org
  - package-ecosystem: "npm"
    directory: "copi.owasp.org"
    schedule:
      interval: "daily"
  # Maintain dependencies for mix for copi.owasp.org
  - package-ecosystem: "mix"
    directory: "copi.owasp.org"
    schedule:
      interval: "daily"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for docker for copi.owasp.org
  - package-ecosystem: "docker"
    directory: "copi.owasp.org"
    schedule:
      interval: "daily"
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: "daily"
  - package-ecosystem: docker
    directory: /.clusterfuzzlite
    schedule:
      interval: daily
