import Config

# Configure your database
config :copi, Copi.Repo,
  username: System.get_env("POSTGRES_USR"),
  password: System.get_env("POSTGRES_PWD"),
  database: System.get_env("POSTGRES_DB"),
  hostname: System.get_env("POSTGRES_HOST"),
  port: System.get_env("POSTGRES_PORT"),
  show_sensitive_data_on_connection_error: true,
  log: false,
  ssl: true
# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :copi, CopiWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json",
  url: [host: "copiweb-048e38bc6ebf.herokuapp.com", port: 443, scheme: "https"],
  force_ssl: [rewrite_on: [:x_forwarded_proto]]

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Copi.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
