export const data = 
{
    "ACM": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/07-access-controls",
    "SC": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/01-secure-by-default/#1-system-configuration-sc",
    "FM": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/01-secure-by-default/#2-file-management-fm",
    "CS": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/01-secure-by-default/#3-cloud-security-cs",
    "SFL": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/02-frameworks-libraries/#1-security-frameworks-and-libraries-sf",
    "SQ": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/03-secure-database-access/#1-secure-queries-sq",
    "SDC": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/03-secure-database-access/#2-secure-database-configuration-sdc",
    "SDA": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/03-secure-database-access/#3-secure-database-authentication-sda",
    "CEC": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/04-encode-escape-data/#1-character-encoding-and-canonicalization-cec",
    "COE": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/04-encode-escape-data/#2-contextual-output-encoding-coe",
    "SSV": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/05-validate-inputs/#1-syntax-and-semantic-validity-ssv",
    "LF": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/05-validate-inputs/#2-libraries-and-frameworks-lf",
    "VSD": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/05-validate-inputs/#3-validate-serialized-data-vsd",
    "FV": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/05-validate-inputs/#4-file-validation-fv",
    "A": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/06-digital-identity/#1-authentication-a",
    "P": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/06-digital-identity/#2-passwords-p",
    "SM": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/06-digital-identity/#3-session-management-sm",
    "AC": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/07-access-controls/#1-access-control-ac",
    "CP": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/08-protect-data/#1-cryptographic-practices-cp",
    "DP": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/08-protect-data/#2-data-protection-dp",
    "SCM": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/08-protect-data/#3-secret-and-credential-management-scm",
    "MM": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/08-protect-data/#4-memory-management-mm",
    "PDR": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/08-protect-data/#5-protect-data-at-rest-pdr",
    "PDT": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/08-protect-data/#6-protect-data-in-transit-pdt",
    "SL": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/09-logging-monitoring/#1-security-logging-sl",
    "SLD": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/09-logging-monitoring/#2-security-logging-design-sld",
    "M": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/09-logging-monitoring/#3-monitoring-m",
    "EE": "https://devguide.owasp.org/en/04-design/02-web-app-checklist/10-handle-errors-exceptions/#1-errors-and-exceptions-ee"
}
