export let data = 
{
    "V1.1":"Secure Software Development Lifecycle Requirements",
    "V1.2":"Authentication Architectural Requirements",
    "V1.3":"Session Management Architectural Requirements",
    "V1.4":"Access Control Architectural Requirements",
    "V1.5":"Input and Output Architectural Requirements",
    "V1.6":"Cryptographic Architectural Requirements",
    "V1.7":"Errors, Logging and Auditing Architectural Requirements",
    "V1.8":"Data Protection and Privacy Architectural Requirements",
    "V1.9":"Communications Architectural Requirements",
    "V1.10":"Malicious Software Architectural Requirements",
    "V1.11":"Business Logic Architectural Requirements",
    "V1.12":"Secure File Upload Architectural Requirements",
    "V1.13":"API Architectural Requirements",
    "V1.14":"Configuration Architectural Requirements",
    "V2.1":"Password Security Requirements",
    "V2.2":"General Authenticator Requirements",
    "V2.3":"Authenticator Lifecycle Requirements",
    "V2.4":"Credential Storage Requirements",
    "V2.5":"Credential Recovery Requirements",
    "V2.6":"Look-up Secret Verifier Requirements",
    "V2.7":"Out of Band Verifier Requirements",
    "V2.8":"Single or Multi Factor One Time Verifier Requirements",
    "V2.9":"Cryptographic Software and Devices Verifier Requirements",
    "V2.10":"Service Authentication Requirements",
    "V3.1":"Fundamental Session Management Requirements",
    "V3.2":"Session Binding Requirements",
    "V3.3":"Session Logout and Timeout Requirements",
    "V3.4":"Cookie-based Session Management",
    "V3.5":"Token-based Session Management",
    "V3.6":"Re-authentication from a Federation or Assertion",
    "V3.7":"Defenses Against Session Management Exploits",
    "V4.1":"General Access Control Design",
    "V4.2":"Operation Level Access Control",
    "V4.3":"Other Access Control Considerations",
    "V5.1":"Input Validation Requirements",
    "V5.2":"Sanitization and Sandboxing Requirements",
    "V5.3":"Output encoding and Injection Prevention Requirements",
    "V5.4":"Memory, String, and Unmanaged Code Requirements",
    "V5.5":"Deserialization Prevention Requirements",
    "V6.1":"Data Classification",
    "V6.2":"Algorithms",
    "V6.3":"Random Values",
    "V6.4":"Secret Management",
    "V7.1":"Log Content Requirements",
    "V7.2":"Log Processing Requirements",
    "V7.3":"Log Protection Requirements",
    "V7.4":"Error Handling",
    "V8.1":"General Data Protection",
    "V8.2":"Client-side Data Protection",
    "V8.3":"Sensitive Private Data",
    "V9.1":"Communications Security Requirements",
    "V9.2":"Server Communications Security Requirements",
    "V10.1":"Code Integrity Controls",
    "V10.2":"Malicious Code Search",
    "V10.3":"Deployed Application Integrity Controls",
    "V11.1":"Business Logic Security Requirements",
    "V12.1":"File Upload Requirements",
    "V12.2":"File Integrity Requirements",
    "V12.3":"File execution Requirements",
    "V12.4":"File Storage Requirements",
    "V12.5":"File Download Requirements",
    "V12.6":"SSRF Protection Requirements",
    "V13.1":"Generic Web Service Security Verification Requirements",
    "V13.2":"RESTful Web Service Verification Requirements",
    "V13.3":"SOAP Web Service Verification Requirements",
    "V13.4":"GraphQL and other Web Service Data Layer Security Requirements",
    "V14.1":"Build",
    "V14.2":"Dependency",
    "V14.3":"Unintended Security Disclosure Requirements",
    "V14.4":"HTTP Security Headers Requirements",
    "V14.5":"Validate HTTP Request Header Requirements",
}