auditConfig:
  ignoreCves: []
  ignoreGhsas:
    - GHSA-vg6x-rcgg-rjx6
    - GHSA-67mh-4wv8-2f99
    - GHSA-mh29-5h37-fv8m
    - GHSA-m56q-vw4c-c2cp
    - GHSA-f7gr-6p89-r883
    - GHSA-h7h7-mm68-gmrc
    - GHSA-crpf-4hrx-3jrp
    - GHSA-33hq-fvwr-56pm
    - GHSA-8qm3-746x-r74r
overrides:
  cookie@<0.7.0: 0.7.2
