---
    name: Comment on PR with Artifacts
    on:
      workflow_call:
      workflow_dispatch:
    permissions:
      contents: read
    jobs:
      hardening:
        name: Hardening
        runs-on: ubuntu-latest
        steps:
          # Make sure we have some code to test
          - name: Harden runner
            uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
            with:
              egress-policy: block
              allowed-endpoints: >
                api.github.com:443
                github-cloud.githubusercontent.com:443
                github.com:443
                motd.ubuntu.com:443
                keys.openpgp.org:443
          - name: Get Artifact URL & PR Info
            env:
              GITHUB_TOKEN: ${{ github.token }}
              OWNER: ${{ github.repository_owner }}
              REPO: ${{ github.event.repository.name }}
              WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
            run: |

              PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
              echo "Previous Job ID: $PREVIOUS_JOB_ID"
              echo "PREVIOUS_JOB_ID=$PREVIOUS_JOB_ID" >> "$GITHUB_ENV"

              ARTIFACT_ID=$(gh api "/repos/$OWNER/$REPO/actions/artifacts" \
                --jq ".artifacts.[] |
                select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
                select(.expired==false) |
                .id")

              echo "ARTIFACT URL: $ARTIFACT_URL"
              echo "ARTIFACT_URL=$ARTIFACT_URL" >> "$GITHUB_ENV"

              PR_NUMBER=$(jq -r '.pull_requests[0].number' \
                  <<< "$WORKFLOW_RUN_EVENT_OBJ")

              echo "PR Number: $PR_NUMBER"
              echo "PR_NUMBER=$PR_NUMBER" >> "$GITHUB_ENV"

              HEAD_SHA=$(jq -r '.pull_requests[0].head.sha' \
                  <<< "$WORKFLOW_RUN_EVENT_OBJ")

              echo "Head sha: $HEAD_SHA"
              echo "HEAD_SHA=$HEAD_SHA" >> "$GITHUB_ENV"

          - name: Update Comment
            env:
              JOB_PATH: "${{ github.server_url }}/${{ github.repository }}/actions/\
                  runs/${{ env.PREVIOUS_JOB_ID }}"
              HEAD_SHA: ${{ env.HEAD_SHA }}
            uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
            with:
              issue-number: ${{ env.PR_NUMBER }}
              body: |-
                  ## Build Preview

                  [![badge]]($JOB_PATH)

                  You can find files attached to the below linked Workflow Run URL (Logs).

                  Please note that files only stay for around 90 days!

                  | Name      | Link
                  --------------------------------------------------------------------
                  | Commit    | ${{ env.HEAD_SHA }}

                  | Logs      | [${{ env.PREVIOUS_JOB_ID }}](${{ env.JOB_PATH }})

                  | Output files | [cornucopia-build-files.${{ github.sha }}.zip](${{ env. ARTIFACT_URL }})

                  [badge]: https://img.shields.io/badge/Build-Success!-3fb950?logo=github&style=for-the-badge
  