---
    name: Comment on PR with Artifacts
    on:
      workflow_call:
      workflow_dispatch:
    permissions:
      contents: read
    jobs:
      hardening:
        permissions:
          contents: read
          pull-requests: none
        uses: ./.github/workflows/hardening.yaml
      comment-on-pr-with-artifacts:
        permissions:
          pull-requests: write
          contents: read
        name: Comment on PR with Artifacts
        runs-on: ubuntu-latest
        steps:
          - name: Get Artifact URL & PR Info
            env:
              WORKFLOW_RUN_EVENT_OBJ: ${{ toJSON(github.event.workflow_run) }}
              GH_TOKEN: ${{ github.token }}
            run: |
              PREVIOUS_JOB_ID=$(jq -r '.id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
              SUITE_ID=$(jq -r '.check_suite_id' <<< "$WORKFLOW_RUN_EVENT_OBJ")
              # Sample for a single artifact, can be improved for a multiple artifacts
              ARTIFACT_ID=$(gh api "/repos/${{ github.repository }}/actions/artifacts" \
                --jq ".artifacts.[] |
                select(.workflow_run.id==${PREVIOUS_JOB_ID}) |
                .id")
              echo "ARTIFACT_URL=https://github.com/${{ github.repository }}/suites/${SUITE_ID}/artifacts/${ARTIFACT_ID}" >> $GITHUB_ENV
              PR_NUMBER=$(jq -r '.pull_requests[0].number' <<< "$WORKFLOW_RUN_EVENT_OBJ")
              echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
          - uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
            env:
              PR_NUMBER: ${{ env.PR_NUMBER }}
              PR_NOTES: |
                Build artifacts:
                | Name | Link |
                |------|------|
                | Output files | [cornucopia-build-files.${{ github.sha }}.zip](${{ env.ARTIFACT_URL }}) |
                [badge]: https://img.shields.io/badge/Build-Success!-3fb950?logo=github&style=for-the-badge
            with:
              script: |
                github.rest.issues.createComment({
                  issue_number: process.env.PR_NUMBER,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: process.env.PR_NOTES
                })