---
  name: Copi Build and Test

  on:
      # Triggers the workflow on push or pull request events but only for the main branch
    pull_request_target:
      paths:
      - 'copi.owasp.org/**'
      - '.github/workflows/copi.yml'
    workflow_dispatch:
  env:
    MIX_ENV: test
    POSTGRES_TEST_PWD: ${{ secrets.POSTGRES_TEST_PWD }}
  permissions:
    contents: read
  jobs:
    build-test:
      runs-on: ubuntu-latest # Or another supported runner
      services:
        postgres:
          image: postgres:14
          env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${{ secrets.POSTGRES_TEST_PWD }}
            POSTGRES_DB: copi_test
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

        - name: Cache deps
          id: cache-deps
          uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
          env:
            cache-name: cache-elixir-deps
          with:
            path: copi.owasp.org/deps
            key: ${{ runner.os }}-mix-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
            restore-keys: |
              ${{ runner.os }}-mix-${{ env.cache-name }}-
        - name: Install Elixir and Erlang
          uses: erlef/setup-beam@8aa8a857c6be0daae6e97272bb299d5b942675a4 # v1.19.0
          with:
            elixir-version: 1.18.2
            otp-version: 27.3.3
          env:
            ImageOS: ubuntu24

        - name: Install dependencies
          working-directory: copi.owasp.org
          run: mix deps.get

        - name: Build the project
          working-directory: copi.owasp.org
          run: mix compile
          
        - name: Run tests
          working-directory: copi.owasp.org
          run: mix test
