---
  name: Copi Deploy Production
  on:
    push:
      tags:
        - "v*"
  permissions:
    contents: read
  jobs:
    deploy-to-prod:
      runs-on: ubuntu-latest # Or another supported runner
      steps:
        - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        - name: Install Elixir and Erlang
          uses: erlef/setup-beam@8e7fdef09ffa3ea54328b5000c170a3b9b20ca96 # v1.20.3
          with:
            elixir-version: 1.18.2
            otp-version: 27.3.3
          env:
            ImageOS: ubuntu24
        - name: Setup Flyctl
          uses: superfly/flyctl-actions/setup-flyctl@63da3ecc5e2793b98a3f2519b3d75d4f4c11cec2
        - name: Deploy to Fly.io production
          run: flyctl deploy --remote-only --app copi-white-forest-5871 --env PHX_HOST=copi.owasp.org
          env:
            FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          working-directory: ./copi.owasp.org