name: Delete artifact branch when pull requests are closed
on:
  pull_request:
    types: [closed]
permissions:
  contents: read

jobs:
  delete-branch:
    permissions:
      contents: write  # for Git to git push
    name: Delete artifact branch
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout target branch
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ github.event.pull_request.head.ref }}-artifacts
      - name: Delete artifact target branch
        id: delete-artifact-target-branch
        env:
          TARGET_BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin :"tmp-$TARGET_BRANCH-artifacts" || echo "Could not delete $TARGET_BRANCH-artifacts"
