name: Delete artifact branch when pull requests are closed
on:
  pull_request:
    types: [closed]
jobs:
  hardening:
    name: Harden runner
    uses: ./.github/workflows/hardening.yaml
  delete-branch:
    name: Delete artifact branch
    needs: hardening
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Delete artifact target branch
        id: delete-artifact-target-branch
        env:
          TARGET_BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin :"tmp-$TARGET_BRANCH-artifacts" || echo "Could not delete tmp-$TARGET_BRANCH-artifacts"
