name: Delete artifact branch when pull requests are closed
on:
  pull_request:
    types: [closed]
jobs:
  hardening:
    name: Harden runner
    uses: ./.github/workflows/hardening.yaml
  delete-branch:
    name: Delete artifact branch
    needs: hardening
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
      - name: Delete artifact target branch
        id: delete-artifact-target-branch
        env:
          TARGET_BRANCH: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin :"tmp-$TARGET_BRANCH-artifacts" || echo "Could not delete tmp-$TARGET_BRANCH-artifacts"
