---
    name: Build and Deploy The Cornucopia Website on Production
    on: 
      push:
        branches: [master]
        paths:
        - 'cornucopia.owasp.org/**'
    permissions:
      contents: read
    jobs:
      hardening:
        name: Hardening
        runs-on: ubuntu-latest
        steps:
          # Make sure we have some code to test
          - name: Harden runner
            uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
            with:
              egress-policy: block
              allowed-endpoints: >
                api.github.com:443
                github-cloud.githubusercontent.com:443
                github.com:443
                motd.ubuntu.com:443
                keys.openpgp.org:443
      build-and-deploy-production:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
          - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
            name: Install pnpm
            with:
              version: 10.0.0
              run_install: false
    
          - name: Install Node.js
            uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
            with:
              node-version: 20.18.2
          - name: Build
            working-directory: cornucopia.owasp.org
            run: |
              pnpm install          # Install dependencies
              npm run build        # Build production version
          - name: Deploy the website
            uses: cloudflare/wrangler-action@392082e81ffbcb9ebdde27400634aa004b35ea37
            with:
              workingDirectory: "cornucopia.owasp.org"
              apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              wranglerVersion: "3.105.1"
              command: pages deploy build --project-name=cornucopia
          - name: Deploy the worker routes
            uses: cloudflare/wrangler-action@392082e81ffbcb9ebdde27400634aa004b35ea37
            with:
                workingDirectory: "cornucopia.owasp.org"
                apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                wranglerVersion: "3.105.1"
                command: deploy script/nonce-worker.js --config script/wrangler.toml --env production