---
    name: Build and Deploy The Cornucopia Website on Staging
    on: 
      pull_request_target:
        paths:
        - 'cornucopia.owasp.org/**'
    permissions:
      contents: read
    jobs:
      hardening:
        name: Hardening
        runs-on: ubuntu-latest
        steps:
          # Make sure we have some code to test
          - name: Harden runner
            uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
            with:
              egress-policy: block
              allowed-endpoints: >
                api.github.com:443
                github-cloud.githubusercontent.com:443
                github.com:443
                motd.ubuntu.com:443
                keys.openpgp.org:443
      build-and-deploy-staging:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            with:
              ref: ${{ github.event.pull_request.head.sha }}
          - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
            name: Install pnpm
            with:
              version: 10.0.0
              run_install: false
    
          - name: Install Node.js
            uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
            with:
              node-version: 20.18.2
          - name: Build
            working-directory: cornucopia.owasp.org
            run: |
              pnpm install          # Install dependencies
              npm run build-stage   # Build staging version
          - name: Deploy the website
            uses: cloudflare/wrangler-action@7a5f8bbdfeedcde38e6777a50fe685f89259d4ca
            with:
              workingDirectory: "cornucopia.owasp.org"
              apiToken: ${{ secrets.CLOUDFLARE_STAGING_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_STAGING_ACCOUNT_ID }}
              wranglerVersion: "3.105.1"
              command: pages deploy build --project-name=cornucopia
          - name: Deploy the worker routes
            uses: cloudflare/wrangler-action@7a5f8bbdfeedcde38e6777a50fe685f89259d4ca
            with:
                workingDirectory: "cornucopia.owasp.org"
                apiToken: ${{ secrets.CLOUDFLARE_STAGING_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_STAGING_ACCOUNT_ID }}
                wranglerVersion: "3.105.1"
                command: deploy script/nonce-worker.js --config script/wrangler.toml --env staging
