---
    name: Build and Deploy The Cornucopia Website on Staging
    on: 
      pull_request:
        paths:
        - 'cornucopia.owasp.org/**'
        - '.github/workflows/deploy-staging.yml'
    permissions:
      contents: read
    jobs:
      hardening:
        name: Hardening
        runs-on: ubuntu-latest
        steps:
          # Make sure we have some code to test
          - name: Harden runner
            uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
            with:
              egress-policy: block
              allowed-endpoints: >
                api.github.com:443
                github-cloud.githubusercontent.com:443
                github.com:443
                motd.ubuntu.com:443
                keys.openpgp.org:443
                registry.npmjs.org:443
      build-and-deploy-staging:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
            with:
              ref: ${{ github.event.pull_request.head.sha }}
          - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
            name: Install pnpm
            with:
              version: 8.6.0
              run_install: false
            
    
          - name: Install Node.js
            uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
            with:
              node-version: 20.18.2
          - name: Install dependencies
            working-directory: cornucopia.owasp.org
            run: |
                pnpm install --loglevel=debug
          - name: Build
            working-directory: cornucopia.owasp.org
            run: |
              pnpm install          # Install dependencies
              npm run build-stage   # Build staging version
          - name: Deploy the website
            uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
            with:
              workingDirectory: "cornucopia.owasp.org"
              apiToken: ${{ secrets.CLOUDFLARE_STAGING_API_TOKEN }}
              accountId: ${{ secrets.CLOUDFLARE_STAGING_ACCOUNT_ID }}
              wranglerVersion: "3.105.1"
              command: pages deploy build --project-name=cornucopia --branch head
          - name: Deploy the worker routes
            uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
            with:
                workingDirectory: "cornucopia.owasp.org"
                apiToken: ${{ secrets.CLOUDFLARE_STAGING_API_TOKEN }}
                accountId: ${{ secrets.CLOUDFLARE_STAGING_ACCOUNT_ID }}
                wranglerVersion: "3.105.1"
                command: deploy script/nonce-worker.js --config script/wrangler.toml --env staging
