name: Secure the pipeline
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  hardening:
    name: Hardening
    runs-on: ubuntu-latest
    steps:
      # Make sure we have some code to test
      - name: Harden runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: block
