---
    name: "pre-release"
    on:
      push:
        branches:
          - "master"
    permissions:
      contents: read

    jobs:
      hardening:
        name: Harden runner
        uses: ./.github/workflows/hardening.yaml
      pre-release:
        needs: hardening
        name: "Pre Release"
        permissions:
          contents: write
        runs-on: ubuntu-latest
        steps:
          # Make sure we have some code to test
          - name: Checkout repository
            uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
          # Set the pip environment up
          - name: Get Python
            uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
            with:
              python-version: '3.10'
              cache: 'pipenv' # caching pip dependencies
          - name: Install dependencies
            run: |
              pip install -r requirements.txt --require-hashes
              pipenv install --ignore-pipfile --dev
          # Run the tests
          - name: Run unit tests
            run: pipenv run python -m unittest discover -s "tests/scripts" -p "*_utest.py"
          - name: Run integration
            run: pipenv run python -m unittest discover -s "tests/scripts" -p "*_itest.py"
          # Test coverage reports
          - name: Check test coverage - run tests
            run: pipenv run coverage run -m unittest discover -s "tests/scripts" -p "*_*test.py"
          - name: Check test coverage - generate xml
            run: pipenv run coverage xml
          - name: Check test coverage - Report
            run: pipenv run coverage report --fail-under 85 scripts/convert*
          # Upload Code COverage for Codeclimate
          - name: Test & publish code coverage
            uses: paambaati/codeclimate-action@b74bb25d2074a4bc16bd06fffc1b299c07b1f886 # v6.0.0
            env:
              CC_TEST_REPORTER_ID: 7482a81acb1b6de49fa6fd2769a014bb9ae8bee408161c23d400b2ac9e95b7cf          
          - name: Generate new output files
            run: |
              pipenv run python scripts/convert.py -l all -t all -s all
          - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1
            name: "Create pre-release"
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              automatic_release_tag: "pre-release"
              prerelease: true
              title: "Latest pre-release"
              files: |
                CHANGELOG.md
                creative-commons-attribution-3.0.txt
                LICENSE
                LICENSE.md
                output/owasp_cornucopia_webapp_cards_en_1.21_dynamic.docx
                output/owasp_cornucopia_webapp_cards_en_1.21_dynamic.idml
                output/owasp_cornucopia_webapp_cards_en_1.21_static.docx
                output/owasp_cornucopia_webapp_cards_en_1.21_static.idml
                output/owasp_cornucopia_webapp_cards_en_1.30_dynamic.docx
                output/owasp_cornucopia_webapp_cards_en_1.30_dynamic.idml
                output/owasp_cornucopia_webapp_cards_en_1.30_dynamic.pdf
                output/owasp_cornucopia_webapp_cards_en_1.30_leaflet.idml
                output/owasp_cornucopia_webapp_cards_en_1.30_static.docx
                output/owasp_cornucopia_webapp_cards_en_1.30_static.idml
                output/owasp_cornucopia_webapp_cards_en_1.30_static.pdf
                output/owasp_cornucopia_webapp_cards_es_1.20_dynamic.docx
                output/owasp_cornucopia_webapp_cards_es_1.20_dynamic.idml
                output/owasp_cornucopia_webapp_cards_es_1.20_static.docx
                output/owasp_cornucopia_webapp_cards_es_1.20_static.idml
                output/owasp_cornucopia_webapp_cards_es_1.30_dynamic.docx
                output/owasp_cornucopia_webapp_cards_es_1.30_dynamic.pdf
                output/owasp_cornucopia_webapp_cards_es_1.30_dynamic.idml
                output/owasp_cornucopia_webapp_cards_es_1.30_leaflet.idml
                output/owasp_cornucopia_webapp_cards_es_1.30_static.docx
                output/owasp_cornucopia_webapp_cards_es_1.30_static.pdf
                output/owasp_cornucopia_webapp_cards_es_1.30_static.idml
                output/owasp_cornucopia_webapp_cards_fr_1.30_dynamic.docx
                output/owasp_cornucopia_webapp_cards_fr_1.30_dynamic.idml
                output/owasp_cornucopia_webapp_cards_fr_1.30_dynamic.pdf
                output/owasp_cornucopia_webapp_cards_fr_1.30_leaflet.idml
                output/owasp_cornucopia_webapp_cards_fr_1.30_static.docx
                output/owasp_cornucopia_webapp_cards_fr_1.30_static.idml
                output/owasp_cornucopia_webapp_cards_fr_1.30_static.pdf
                output/owasp_cornucopia_webapp_cards_nl_1.30_dynamic.docx
                output/owasp_cornucopia_webapp_cards_nl_1.30_dynamic.idml
                output/owasp_cornucopia_webapp_cards_nl_1.30_dynamic.pdf
                output/owasp_cornucopia_webapp_cards_nl_1.30_leaflet.idml
                output/owasp_cornucopia_webapp_cards_nl_1.30_static.docx
                output/owasp_cornucopia_webapp_cards_nl_1.30_static.idml
                output/owasp_cornucopia_webapp_cards_nl_1.30_static.pdf
                output/owasp_cornucopia_webapp_cards_no-nb_1.30_dynamic.docx
                output/owasp_cornucopia_webapp_cards_no-nb_1.30_dynamic.idml
                output/owasp_cornucopia_webapp_cards_no-nb_1.30_dynamic.pdf
                output/owasp_cornucopia_webapp_cards_no-nb_1.30_leaflet.idml
                output/owasp_cornucopia_webapp_cards_no-nb_1.30_static.docx
                output/owasp_cornucopia_webapp_cards_no-nb_1.30_static.idml
                output/owasp_cornucopia_webapp_cards_no-nb_1.30_static.pdf
                output/owasp_cornucopia_webapp_cards_pt-br_1.30_dynamic.docx
                output/owasp_cornucopia_webapp_cards_pt-br_1.30_dynamic.idml
                output/owasp_cornucopia_webapp_cards_pt-br_1.30_dynamic.pdf
                output/owasp_cornucopia_webapp_cards_pt-br_1.30_leaflet.idml
                output/owasp_cornucopia_webapp_cards_pt-br_1.30_static.docx
                output/owasp_cornucopia_webapp_cards_pt-br_1.30_static.idml
                output/owasp_cornucopia_webapp_cards_pt-br_1.30_static.pdf
                output/owasp_cornucopia_mobileapp_cards_en_1.00_static.idml
                output/owasp_cornucopia_mobileapp_cards_en_1.00_leaflet.idml
                README.md
                source/*.yaml
                resources/case/*
