---
    name: "pre-release"
    on:
      push:
        branches:
          - "master"
    permissions:
      contents: read

    jobs:
      hardening:
        name: Harden runner
        uses: ./.github/workflows/hardening.yaml
      pre-release:
        needs: hardening
        name: "Pre Release"
        permissions:
          contents: write
        runs-on: ubuntu-latest
        steps:
          # Make sure we have some code to test
          - name: Checkout repository
            uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
          # Set the pip environment up
          - name: Get Python
            uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
            with:
              python-version: '3.10'
              cache: 'pipenv' # caching pip dependencies
          - name: Install dependencies
            run: |
              pip install -r requirements.txt --require-hashes
              pipenv install --ignore-pipfile --dev
          # Run the tests
          - name: Run unit tests
            run: pipenv run python -m unittest discover -s "tests/scripts" -p "*_utest.py"
          - name: Run integration
            run: pipenv run python -m unittest discover -s "tests/scripts" -p "*_itest.py"
          # Test coverage reports
          - name: Check test coverage - run tests
            run: pipenv run coverage run -m unittest discover -s "tests/scripts" -p "*_*test.py"
          - name: Check test coverage - generate xml
            run: pipenv run coverage xml
          - name: Check test coverage - Report
            run: pipenv run coverage report --fail-under 85 scripts/convert*
          # Upload Code COverage for Codeclimate
          - name: Test & publish code coverage
            uses: paambaati/codeclimate-action@b74bb25d2074a4bc16bd06fffc1b299c07b1f886 # v6.0.0
            env:
              CC_TEST_REPORTER_ID: 7482a81acb1b6de49fa6fd2769a014bb9ae8bee408161c23d400b2ac9e95b7cf          
          - name: Generate new output files
            run: |
              pipenv run python scripts/convert.py -l all -lt all -t all -v 1.22 -e webapp
              pipenv run python scripts/convert.py -l all -lt all -t all -v 2.00 -e webapp
              pipenv run python scripts/convert.py -l en -lt all -t all -v 1.00 -e mobileapp
          - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1
            name: "Create pre-release"
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              automatic_release_tag: "pre-release"
              prerelease: true
              title: "Latest pre-release"
              files: |
                CHANGELOG.md
                creative-commons-attribution-3.0.txt
                LICENSE
                LICENSE.md
                output/owasp_cornucopia_webapp_1.22_cards_en_static.idml
                output/owasp_cornucopia_webapp_1.22_cards_es_static.idml
                output/owasp_cornucopia_webapp_1.22_cards_fr_static.idml
                output/owasp_cornucopia_webapp_1.22_cards_nl_static.idml
                output/owasp_cornucopia_webapp_1.22_cards_no-nb_static.idml
                output/owasp_cornucopia_webapp_1.22_cards_pt-br_static.idml
                output/owasp_cornucopia_webapp_1.22_guide_en_static.docx
                output/owasp_cornucopia_webapp_1.22_guide_es_static.docx
                output/owasp_cornucopia_webapp_1.22_guide_fr_static.docx
                output/owasp_cornucopia_webapp_1.22_guide_nl_static.docx
                output/owasp_cornucopia_webapp_1.22_guide_no-nb_static.docx
                output/owasp_cornucopia_webapp_1.22_guide_pt-br_static.docx
                output/owasp_cornucopia_webapp_1.22_leaflet_en_static.idml
                output/owasp_cornucopia_webapp_1.22_leaflet_es_static.idml
                output/owasp_cornucopia_webapp_1.22_leaflet_fr_static.idml
                output/owasp_cornucopia_webapp_1.22_leaflet_nl_static.idml
                output/owasp_cornucopia_webapp_1.22_leaflet_no-nb_static.idml
                output/owasp_cornucopia_webapp_1.22_leaflet_pt-br_static.idml
                output/owasp_cornucopia_webapp_2.00_cards_en_80x120mm.idml
                output/owasp_cornucopia_webapp_2.00_cards_es_80x120mm.idml
                output/owasp_cornucopia_webapp_2.00_cards_fr_80x120mm.idml
                output/owasp_cornucopia_webapp_2.00_cards_nl_80x120mm.idml
                output/owasp_cornucopia_webapp_2.00_cards_pt-br_80x120mm.idml
                output/owasp_cornucopia_webapp_2.00_cards_no-nb_80x120mm.idml
                output/owasp_cornucopia_webapp_2.00_cards_en_static.idml
                output/owasp_cornucopia_webapp_2.00_cards_es_static.idml
                output/owasp_cornucopia_webapp_2.00_cards_fr_static.idml
                output/owasp_cornucopia_webapp_2.00_cards_nl_static.idml
                output/owasp_cornucopia_webapp_2.00_cards_no-nb_static.idml
                output/owasp_cornucopia_webapp_2.00_cards_pt-br_static.idml
                output/owasp_cornucopia_webapp_2.00_guide_en_static.docx
                output/owasp_cornucopia_webapp_2.00_guide_es_static.docx
                output/owasp_cornucopia_webapp_2.00_guide_fr_static.docx
                output/owasp_cornucopia_webapp_2.00_guide_nl_static.docx
                output/owasp_cornucopia_webapp_2.00_guide_no-nb_static.docx
                output/owasp_cornucopia_webapp_2.00_guide_pt-br_static.docx
                output/owasp_cornucopia_webapp_2.00_leaflet_en_static.idml
                output/owasp_cornucopia_webapp_2.00_leaflet_es_static.idml
                output/owasp_cornucopia_webapp_2.00_leaflet_fr_static.idml
                output/owasp_cornucopia_webapp_2.00_leaflet_nl_static.idml
                output/owasp_cornucopia_webapp_2.00_leaflet_no-nb_static.idml
                output/owasp_cornucopia_webapp_2.00_leaflet_pt-br_static.idml
                output/owasp_cornucopia_mobileapp_1.00_cards_en_80x120mm.idml
                output/owasp_cornucopia_mobileapp_1.00_cards_en_static.idml
                output/owasp_cornucopia_mobileapp_1.00_leaflet_en_static.idml
                README.md
                source/*.yaml
                resources/case/*
