---
    name: "tagged-release"
    
    on:
      push:
        tags:
          - "v*"
    jobs:
      tagged-release:
        name: "Tagged Release"
        permissions:
          contents: write
        runs-on: "ubuntu-latest"
        steps:
          # Make sure we have some code to test
          - name: Harden Runner
            uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
            with:
              egress-policy: block 
              allowed-endpoints: >
                api.github.com:443
                azure.archive.ubuntu.com:80
                esm.ubuntu.com:443
                files.pythonhosted.org:443
                github-cloud.githubusercontent.com:443
                github.com:443
                motd.ubuntu.com:443
                packages.microsoft.com:443
                ppa.launchpadcontent.net:443
                pypi.org:443
                opencre.org:443
                codeclimate.com:443
                d3iz1jjs17r6kg.cloudfront.net:443
                keys.openpgp.org:443
                api.codeclimate.com:443
                uploads.github.com:443
          - name: Checkout repository
            uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
          # Set the pip environment up
          - name: Get Python
            uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
            with:
              python-version: '3.10'
              cache: 'pipenv' # caching pip dependencies
          - name: Install dependencies
            run: |
              pip install -r requirements.txt --require-hashes
              pipenv install --ignore-pipfile --dev
          # Run the tests
          - name: Run unit tests
            run: pipenv run python -m unittest discover -s "tests/scripts" -p "*_utest.py"
          - name: Run integration
            run: pipenv run python -m unittest discover -s "tests/scripts" -p "*_itest.py"
          # Test coverage reports
          - name: Check test coverage - run tests
            run: pipenv run coverage run -m unittest discover -s "tests/scripts" -p "*_*test.py"
          - name: Check test coverage - generate xml
            run: pipenv run coverage xml
          - name: Check test coverage - Report
            run: pipenv run coverage report --fail-under 85 scripts/convert*        
          - name: Generate new output files
            run: |
              pipenv run python scripts/convert.py -l all -t all -s all
          - uses: marvinpinto/action-automatic-releases@919008cf3f741b179569b7a6fb4d8860689ab7f0 # v1.2.1
            name: "Create release"
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              prerelease: false
              files: |
                CHANGELOG.md
                creative-commons-attribution-3.0.txt
                LICENSE
                LICENSE.md
                output/owasp_cornucopia_ecommerce_cards_en_1.21_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_en_1.21_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_en_1.21_static.docx
                output/owasp_cornucopia_ecommerce_cards_en_1.21_static.idml
                output/owasp_cornucopia_ecommerce_cards_en_1.30_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_en_1.30_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_en_1.30_dynamic.pdf
                output/owasp_cornucopia_ecommerce_cards_en_1.30_static.docx
                output/owasp_cornucopia_ecommerce_cards_en_1.30_static.idml
                output/owasp_cornucopia_ecommerce_cards_en_1.30_static.pdf
                output/owasp_cornucopia_ecommerce_cards_es_1.20_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_es_1.20_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_es_1.20_static.docx
                output/owasp_cornucopia_ecommerce_cards_es_1.20_static.idml
                output/owasp_cornucopia_ecommerce_cards_fr_1.20_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_fr_1.20_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_fr_1.20_static.docx
                output/owasp_cornucopia_ecommerce_cards_fr_1.20_static.idml
                output/owasp_cornucopia_ecommerce_cards_fr_1.30_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_fr_1.30_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_fr_1.30_dynamic.pdf
                output/owasp_cornucopia_ecommerce_cards_fr_1.30_static.docx
                output/owasp_cornucopia_ecommerce_cards_fr_1.30_static.idml
                output/owasp_cornucopia_ecommerce_cards_fr_1.30_static.pdf
                output/owasp_cornucopia_ecommerce_cards_nl_1.21_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_nl_1.21_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_nl_1.21_static.docx
                output/owasp_cornucopia_ecommerce_cards_nl_1.21_static.idml
                output/owasp_cornucopia_ecommerce_cards_nl_1.30_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_nl_1.30_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_nl_1.30_dynamic.pdf
                output/owasp_cornucopia_ecommerce_cards_nl_1.30_static.docx
                output/owasp_cornucopia_ecommerce_cards_nl_1.30_static.idml
                output/owasp_cornucopia_ecommerce_cards_nl_1.30_static.pdf
                output/owasp_cornucopia_ecommerce_cards_no-nb_1.30_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_no-nb_1.30_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_no-nb_1.30_dynamic.pdf
                output/owasp_cornucopia_ecommerce_cards_no-nb_1.30_static.docx
                output/owasp_cornucopia_ecommerce_cards_no-nb_1.30_static.idml
                output/owasp_cornucopia_ecommerce_cards_no-nb_1.30_static.pdf
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.20_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.20_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.20_static.docx
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.20_static.idml
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.30_dynamic.docx
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.30_dynamic.idml
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.30_dynamic.pdf
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.30_static.docx
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.30_static.idml
                output/owasp_cornucopia_ecommerce_cards_pt-br_1.30_static.pdf
                README.md
                source/*.yaml